name: Build and Push Docker Image

on:
  push:
    branches:
      - test/test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          echo "hello"
          # Your actual Docker build commands go here
